apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        test: test
    spec:
      containers:
        - name: frontend
          image: gangadhar0416/frontend:TAG
          ports:
            - containerPort: 80
          imagePullPolicy: Always
